### ISSUE TITLE
Mappings Submodule needs update

### ISSUE THREAD

**Issue by Hellohi3654** [bundabrg/Geyser#11]
Sorry I'm not following the bug report 

But this is just a reminder that you need to update your mappings submodule
as davchoo's pick block fix requires a submodule update

**Comment by bundabrg** [comment]
Thanks, I thought I merged in from master but obviously I've mucked up something. Git submodules are always a bit of a mystery. I'll have a look tomorrow.

In your repo are you merging from master or using me as an upstream at all? The need fro my bleeding build is starting to be less needed as extensions are starting to hopefully stabilize and I was going to start building extensions that provide the stuff I've merged in (such as spaces in username etc)

**Comment by Hellohi3654** [comment]
I used to use your bleeding branch as a upstream that's why my main branch is called bundabrg-bleeding but now I'm using the master branch as my upstream and merging in PRs that seem stable and add needed changes

Also can't wait for more extensions 👍

**Comment by bundabrg** [comment]
Sorted in b52. I've also stripped out improved login for the moment since it may no longer be required (and means a smaller diff).

I've also added a note in README.md that has a link to your repo as well.

**Comment by Hellohi3654** [comment]
Thanks
I'll remove improved login from my repo as well
Won't floodgate 2.0 fix all that?

**Comment by bundabrg** [comment]
Improved login was supposed to reorder some things around to make the login smoother (nothing really to do with authentication) but I think too much has changed and so may need another look if indeed its still a problem at all (my server login seemed an ok speed). I think I was getting some null pointer exceptions by new Geyser code that assumed some things would not be null directly due to those other changes.

**Comment by Hellohi3654** [comment]
Yeah ok
